# -*- coding: utf-8 -*-
"""logistic_regression_sklearn_fashion_mnist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10c2IqR_z6QT64J7Aes_Ce88kXjoBuo2T
"""

from keras.datasets import fashion_mnist
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

X_train.shape

X_train_final = X_train.reshape((-1, 784))

X_test_final = X_test.reshape((-1, 784))

X_train_final =  X_train_final / 255
X_test_final =  X_test_final / 255

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train_final, y_train)

y_pred = model.predict(X_test_final)
y_pred

from sklearn.metrics import accuracy_score
acc_score = accuracy_score(y_test, y_pred)*100
acc_score