# -*- coding: utf-8 -*-
"""logistic_regression_sklearn_binary_classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TRiyGF4EVIflKWh8cZaPJ6UscZISqM2O
"""

from sklearn.linear_model import LogisticRegression

from keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train.shape

X_train_binary= X_train[(y_train==0) | (y_train==1)]
y_train_binary= y_train[(y_train==0) | (y_train==1)]

print(y_train[0:10]) 
print(y_train_binary[0:10])

X_train_final = X_train_binary.reshape((-1, 784))

X_test_binary= X_test[(y_test==0) | (y_test==1)]
y_test_binary= y_test[(y_test==0) | (y_test==1)]

X_test_final = X_test_binary.reshape((-1, 784))

X_train_final =  X_train_final / 255
X_test_final =  X_test_final / 255

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train_final, y_train_binary)

y_pred = model.predict(X_test_final)
y_pred

from sklearn.metrics import accuracy_score
acc_score = accuracy_score(y_test_binary, y_pred)*100
acc_score

import matplotlib.pyplot as plt
plt.imshow(X_test_binary[5],cmap="gray")
print(y_pred[5])