# -*- coding: utf-8 -*-
"""logistic_regression_keras_cifar10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k6yoLKl99oE99HRVUaIlPIlcRI7xoV-A
"""

import numpy as np
from tensorflow import keras
print (keras.__version__)

from keras.datasets import cifar10
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

X_train.shape

y_train[:10]

X_train_final = X_train.reshape(-1,3072)
X_train_final.shape

X_test_final = X_test.reshape(-1,3072)
X_test_final.shape

X_train_final = X_train_final / 255
X_test_final = X_test_final / 255

model = keras.Sequential()
model.add(keras.layers.Dense(10, input_shape= (3072,), activation = 'softmax'))

model.summary()

model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

results = model.fit(
    x = X_train_final,
    y = y_train,
    shuffle = True,
    epochs = 30,
    batch_size = 16,
    validation_data = (X_test_final, y_test)
)

import matplotlib.pyplot as plt

plt.plot(results.history['loss'])
plt.plot(results.history['val_loss'])
plt.legend(['Training', 'Validation'])
plt.title('Training and Validation Losses')
plt.xlabel('epoch')
plt.ylabel('Losses')

plt.plot(results.history['accuracy'])
plt.plot(results.history['val_accuracy'])
plt.legend(['Training', 'Validation'])
plt.title('Training and Validation accuarcy')
plt.xlabel('epoch')
plt.ylabel('accuarcy')